### ISSUE TITLE
After migration to 1.1.0 linting throws error

### ISSUE THREAD

**Issue by jmicans** [ventx/helm3-ci#1]
Hello, 
I was using latest helm3-ci version to do helm chart linting during ci pipeline. 
Version 1.1.0 broke the pipeline. This error is thrown:
`Error: Error loading configuration: 'chart_schema.yaml' neither specified nor found in default locations`

Is there a fix or a possible workaround?

**Comment by hajowieland** [comment]
This seems to be caused by the update of [chart-testing](https://github.com/helm/chart-testing) from **3.0.0-rc.1** to the latest **3.3.1** version.

Can you elaborate on which commands you use for your pipeline using the helm3-ci container?

As an alternative you can just switch back to the previous version **1.0.1**

**Comment by jmicans** [comment]
Thanks, switching to 1.0.1 helped. 
I'm using `ct lint --charts <chart root folder>`

**Comment by hajowieland** [comment]
Great - the Docker versions are always tagged matching the git tags.

BTW:
We are using the following command

`ct lint --config ci/ct.yaml --chart-yaml-schema ci/chart_schema.yaml --lint-conf ci/lintconf.yaml`
